<?php

namespace justinholtweb\rabbits\services;

use craft\base\Component;
use craft\helpers\Html;
use justinholtweb\rabbits\elements\Component as ComponentElement;

/**
 * Compiles a component's JSON tree into a Twig partial
 */
class TwigCompiler extends Component
{
    /**
     * Compile a component element into Twig markup
     */
    public function compile(ComponentElement $component): string
    {
        $tree = $component->getTreeArray();

        if (empty($tree)) {
            return '{# Empty component: ' . ($component->handle ?? 'unknown') . ' #}';
        }

        $lines = [];
        $lines[] = '{# Component: ' . ($component->title ?? $component->handle) . ' #}';
        $lines[] = '{# Auto-generated by Rabbits — do not edit manually #}';
        $lines[] = '';

        $lines[] = $this->compileNode($tree, 0);

        return implode("\n", $lines);
    }

    /**
     * Compile a single node and its children
     */
    public function compileNode(array $node, int $depth = 0): string
    {
        $indent = str_repeat('  ', $depth);
        $type = $node['type'] ?? 'container';

        return match ($type) {
            'heading', 'text', 'link', 'button' => $this->compileTextNode($node, $indent, $depth),
            'image' => $this->compileImageNode($node, $indent),
            'divider' => $this->compileSelfClosingNode($node, $indent),
            'spacer' => $this->compileEmptyNode($node, $indent),
            default => $this->compileContainerNode($node, $indent, $depth),
        };
    }

    /**
     * Compile a container node (div, section, etc.) with children
     */
    private function compileContainerNode(array $node, string $indent, int $depth): string
    {
        $tag = $node['tag'] ?? 'div';
        $attrs = $this->buildAttributes($node);
        $lines = [];

        $lines[] = $indent . '<' . $tag . $attrs . '>';

        if (!empty($node['children'])) {
            foreach ($node['children'] as $child) {
                $lines[] = $this->compileNode($child, $depth + 1);
            }
        }

        $lines[] = $indent . '</' . $tag . '>';

        return implode("\n", $lines);
    }

    /**
     * Compile a text-bearing node (heading, paragraph, link, button)
     */
    private function compileTextNode(array $node, string $indent, int $depth): string
    {
        $tag = $node['tag'] ?? 'span';
        $attrs = $this->buildAttributes($node);
        $content = $this->compileContent($node['content'] ?? null);

        // Links and buttons get href
        if (in_array($tag, ['a']) && isset($node['href'])) {
            $href = $this->compileHref($node['href']);
            $attrs = ' href="' . $href . '"' . $attrs;
        }

        // If the node has children (e.g., a link wrapping other elements), render them
        if (!empty($node['children'])) {
            $lines = [];
            $lines[] = $indent . '<' . $tag . $attrs . '>';
            foreach ($node['children'] as $child) {
                $lines[] = $this->compileNode($child, $depth + 1);
            }
            $lines[] = $indent . '</' . $tag . '>';
            return implode("\n", $lines);
        }

        return $indent . '<' . $tag . $attrs . '>' . $content . '</' . $tag . '>';
    }

    /**
     * Compile an image node
     */
    private function compileImageNode(array $node, string $indent): string
    {
        $attrs = $this->buildAttributes($node);
        $src = $this->compileSrc($node['src'] ?? null);
        $alt = Html::encode($node['alt'] ?? '');

        return $indent . '<img src="' . $src . '" alt="' . $alt . '"' . $attrs . ' />';
    }

    /**
     * Compile a self-closing node (hr)
     */
    private function compileSelfClosingNode(array $node, string $indent): string
    {
        $tag = $node['tag'] ?? 'hr';
        $attrs = $this->buildAttributes($node);

        return $indent . '<' . $tag . $attrs . ' />';
    }

    /**
     * Compile an empty node (spacer)
     */
    private function compileEmptyNode(array $node, string $indent): string
    {
        $tag = $node['tag'] ?? 'div';
        $attrs = $this->buildAttributes($node);

        return $indent . '<' . $tag . $attrs . '></' . $tag . '>';
    }

    /**
     * Build HTML attributes string from node
     */
    private function buildAttributes(array $node): string
    {
        $attrs = [];

        // CSS classes
        $classes = $this->buildClassList($node);
        if (!empty($classes)) {
            $attrs[] = 'class="' . implode(' ', $classes) . '"';
        }

        // Inline styles from the default breakpoint
        $style = $this->buildInlineStyle($node);
        if ($style) {
            $attrs[] = 'style="' . $style . '"';
        }

        // Data attribute for node identification (useful for Smoke integration)
        if (isset($node['id'])) {
            $attrs[] = 'data-rabbits-node="' . Html::encode($node['id']) . '"';
        }

        // Animation data attributes
        if (!empty($node['animations'])) {
            $attrs[] = $this->buildAnimationAttributes($node['animations']);
        }

        return $attrs ? ' ' . implode(' ', $attrs) : '';
    }

    /**
     * Build CSS class list for a node
     */
    private function buildClassList(array $node): array
    {
        $classes = [];

        if (!empty($node['classes'])) {
            $classes = array_merge($classes, (array) $node['classes']);
        }

        return $classes;
    }

    /**
     * Build inline style string from default styles
     */
    private function buildInlineStyle(array $node): string
    {
        $styles = $node['styles']['default'] ?? [];

        if (empty($styles)) {
            return '';
        }

        $parts = [];
        foreach ($styles as $property => $value) {
            $cssProperty = $this->camelToKebab($property);
            $parts[] = $cssProperty . ': ' . $value;
        }

        return implode('; ', $parts);
    }

    /**
     * Build animation data attributes
     */
    private function buildAnimationAttributes(array $animations): string
    {
        $attrs = [];

        if (isset($animations['trigger'])) {
            $attrs[] = 'data-rabbits-animate="' . Html::encode($animations['trigger']) . '"';
        }

        if (isset($animations['keyframes'])) {
            $attrs[] = "data-rabbits-keyframes='" . json_encode($animations['keyframes'], JSON_HEX_APOS) . "'";
        }

        if (isset($animations['options'])) {
            $attrs[] = "data-rabbits-options='" . json_encode($animations['options'], JSON_HEX_APOS) . "'";
        }

        return implode(' ', $attrs);
    }

    /**
     * Compile content value — handles static text and field bindings
     */
    private function compileContent(?array $content): string
    {
        if (!$content) {
            return '';
        }

        return match ($content['type'] ?? 'static') {
            'static' => Html::encode($content['value'] ?? ''),
            'field' => '{{ ' . ($content['binding'] ?? 'entry.title') . ' }}',
            'twig' => $content['value'] ?? '',
            default => Html::encode($content['value'] ?? ''),
        };
    }

    /**
     * Compile href value
     */
    private function compileHref(string $href): string
    {
        // If it looks like a Twig expression, pass through
        if (str_contains($href, '{{') || str_contains($href, '{%')) {
            return $href;
        }

        return Html::encode($href);
    }

    /**
     * Compile image src — handles static URL and field bindings
     */
    private function compileSrc(?array $src): string
    {
        if (!$src) {
            return '';
        }

        return match ($src['type'] ?? 'static') {
            'static' => Html::encode($src['value'] ?? ''),
            'field' => '{{ ' . ($src['binding'] ?? 'entry.image.one().url') . ' }}',
            'asset' => '{{ ' . ($src['binding'] ?? 'entry.image.one().url') . ' }}',
            default => Html::encode($src['value'] ?? ''),
        };
    }

    /**
     * Convert camelCase to kebab-case for CSS properties
     */
    private function camelToKebab(string $str): string
    {
        return strtolower(preg_replace('/([a-z])([A-Z])/', '$1-$2', $str));
    }
}
